// ==================== RESORT TRAIL SVG BUILDER ====================
// Generates an SVG string with the real OSM-derived resort map as a background
// image and optional overlay layers: land tints, GPS trail, trip item markers.
// Returns a raw SVG string — no React dependency.
//
// Layer order (bottom → top):
//   1. resort-map.svg base image (buildings, roads, water)
//   2. Land overlays (semi-transparent tinted polygons)
//   3. GPS trail polyline + start/end markers
//   4. Trip item markers
//
// The map image (resort-map.svg) was generated by scripts/build-resort-map.py
// from OpenStreetMap data © OpenStreetMap contributors, ODbL.
// https://www.openstreetmap.org/copyright
//
// Coordinate system — all layers use the same bounds:
//   x = (lng - WEST) / (EAST - WEST) * SVG_W
//   y = (NORTH - lat) / (NORTH - SOUTH) * SVG_H

// ==================== BOUNDING BOX ====================
// Must match the constants in scripts/build-resort-map.py exactly.

const NORTH =  33.81619;
const SOUTH =  33.80350;
const EAST  = -117.91546;
const WEST  = -117.92837;

// The generated resort-map.svg canvas dimensions (must match script output)
const MAP_W = 900;
const MAP_H = 1064;

// ==================== COORDINATE MAPPING ====================

function toSVG(lat: number, lng: number): { x: number; y: number } {
  const x = ((lng - WEST)  / (EAST  - WEST))  * MAP_W;
  const y = ((NORTH - lat) / (NORTH - SOUTH)) * MAP_H;
  return { x: Math.round(x * 10) / 10, y: Math.round(y * 10) / 10 };
}

// ==================== TYPES ====================

export interface MapMarker {
  lat: number;
  lng: number;
  /** Fill color for the marker circle */
  color: string;
  /** Single emoji or short text shown inside the marker */
  icon: string;
  /**
   * Label shown below the marker.
   * Use "|" as a separator to render two lines: "HH:MM AM|Attraction Name"
   */
  label?: string;
}

/**
 * A single GeoJSON Feature from land-overlays.geojson.
 * Coordinates follow GeoJSON convention: [lng, lat].
 */
export interface LandOverlayFeature {
  type: "Feature";
  properties: { name?: string; color?: string; opacity?: number };
  geometry: {
    type: "Polygon" | "MultiPolygon";
    coordinates: number[][][] | number[][][][];
  };
}

// ==================== LAND OVERLAY ====================

/**
 * Build the land-tint layer from live GeoJSON features (land-overlays.geojson).
 * GeoJSON coordinates are [lng, lat]; toSVG() expects (lat, lng) — we flip them.
 */
function buildLandOverlaySVG(
  scale: number,
  landFeatures: LandOverlayFeature[]
): string {
  if (!landFeatures.length) return "<!-- no land overlays -->";

  const paths: string[] = [];

  for (const f of landFeatures) {
    const name    = f.properties?.name    ?? "";
    const color   = f.properties?.color   ?? "#888888";
    const opacity = f.properties?.opacity ?? 0.28;
    const safe    = name.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

    // Collect outer rings (index 0 of each polygon)
    const outerRings: number[][][] =
      f.geometry.type === "Polygon"
        ? [(f.geometry.coordinates as number[][][])[0]]
        : (f.geometry.coordinates as number[][][][]).map((poly) => poly[0]);

    for (const ring of outerRings) {
      const pts = ring
        .map(([lng, lat]) => {
          const { x, y } = toSVG(lat, lng);
          return `${(x * scale).toFixed(1)},${(y * scale).toFixed(1)}`;
        })
        .join(" ");
      paths.push(
        `<polygon points="${pts}" fill="${color}" opacity="${opacity}" stroke="${color}" stroke-width="0.5" stroke-opacity="0.4"><title>${safe}</title></polygon>`
      );
    }
  }

  return `
  <!-- Land overlays (land-overlays.geojson) -->
  <g id="land-overlays" pointer-events="none">
    ${paths.join("\n    ")}
  </g>`;
}

// ==================== MARKER OVERLAY ====================

function buildMarkersSVG(markers: MapMarker[], scale: number): string {
  if (!markers.length) return "";

  // Larger base sizes so labels are legible at PDF resolution
  const r    = Math.max(8,  Math.round(10 * scale));
  const fs   = Math.max(10, Math.round(12 * scale)); // icon font-size
  const lfs  = Math.max(8,  Math.round(9  * scale)); // label font-size

  const elements = markers.map(({ lat, lng, color, icon, label }) => {
    const { x, y } = toSVG(lat, lng);
    const cx = (x * scale).toFixed(1);
    const cy = (y * scale).toFixed(1);

    // Two-line label: split on "|" → [timePart, titlePart]
    const parts    = (label ?? "").split("|");
    const timePart = parts[0]?.trim() ?? "";
    const titlePart= parts[1]?.trim() ?? "";

    const baseY = parseFloat(cy) + r + 3;
    const timeEl = timePart
      ? `<text x="${cx}" y="${(baseY + lfs).toFixed(1)}" text-anchor="middle" font-family="sans-serif" font-size="${lfs}" font-weight="600" fill="#111" opacity="0.95">${timePart.slice(0, 10)}</text>`
      : "";
    const titleEl = titlePart
      ? `<text x="${cx}" y="${(baseY + lfs + lfs + 1).toFixed(1)}" text-anchor="middle" font-family="sans-serif" font-size="${lfs - 1}" fill="#222" opacity="0.85">${titlePart.slice(0, 20)}</text>`
      : "";

    return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${color}" stroke="#fff" stroke-width="${(2 * scale).toFixed(1)}" opacity="0.95"/>
    <text x="${cx}" y="${(parseFloat(cy) + fs * 0.38).toFixed(1)}" text-anchor="middle" font-size="${fs}" dominant-baseline="middle">${icon}</text>
    ${timeEl}
    ${titleEl}`;
  });

  return `
  <!-- Trip item markers -->
  <g id="trip-markers">
    ${elements.join("\n    ")}
  </g>`;
}

// ==================== MAIN EXPORT ====================

export function buildResortTrailSVG(
  points: Array<{ lat: number; lng: number }>,
  options?: {
    /** Override canvas width (image scales proportionally). Default: MAP_W */
    width?: number;
    /** Base URL for the resort-map.svg image. Default: "/images/resort-map.svg" */
    mapImageUrl?: string;
    /**
     * Show semi-transparent land tint overlays.
     * Default: false (opt-in to avoid cluttering PDF output).
     */
    showLands?: boolean;
    /**
     * GeoJSON FeatureCollection from land-overlays.geojson.
     * When provided together with showLands:true, this data is used instead of
     * the bundled RESORT_LANDS so edits to the GeoJSON file are reflected.
     */
    landGeoJSON?: { features: LandOverlayFeature[] };
    /** Trip item markers to plot on the map */
    markers?: MapMarker[];
  }
): string {
  const width     = options?.width ?? MAP_W;
  const height    = Math.round(width * (MAP_H / MAP_W));
  const scale     = width / MAP_W;
  const mapUrl    = options?.mapImageUrl ?? "/images/resort-map.svg";
  const showLands = options?.showLands ?? false;
  const markers   = options?.markers ?? [];

  // ==================== LAND OVERLAYS ====================

  const landFeatures = options?.landGeoJSON?.features ?? [];
  const landSVG = showLands ? buildLandOverlaySVG(scale, landFeatures) : "";

  // ==================== GPS TRAIL ====================

  let trailSVG = "";

  if (points.length >= 2) {
    const ptStrings = points
      .map((p) => {
        const { x, y } = toSVG(p.lat, p.lng);
        return `${(x * scale).toFixed(1)},${(y * scale).toFixed(1)}`;
      })
      .join(" ");

    const startPt = toSVG(points[0].lat, points[0].lng);
    const endPt   = toSVG(points[points.length - 1].lat, points[points.length - 1].lng);
    const sx = (startPt.x * scale).toFixed(1);
    const sy = (startPt.y * scale).toFixed(1);
    const ex = (endPt.x * scale).toFixed(1);
    const ey = (endPt.y * scale).toFixed(1);
    const r  = Math.max(4, Math.round(5 * scale));

    trailSVG = `
  <!-- GPS trail -->
  <polyline
    points="${ptStrings}"
    fill="none"
    stroke="#E74C3C"
    stroke-width="${(2.5 * scale).toFixed(1)}"
    stroke-linecap="round"
    stroke-linejoin="round"
    opacity="0.9"
  />
  <!-- Start marker -->
  <circle cx="${sx}" cy="${sy}" r="${r}" fill="#27AE60" stroke="#fff" stroke-width="${(1.5 * scale).toFixed(1)}"/>
  <!-- End marker -->
  <rect
    x="${((endPt.x * scale) - r).toFixed(1)}"
    y="${((endPt.y * scale) - r).toFixed(1)}"
    width="${r * 2}" height="${r * 2}"
    fill="#E74C3C" stroke="#fff" stroke-width="${(1.5 * scale).toFixed(1)}"
  />`;
  }

  // ==================== TRIP MARKERS ====================

  const markerSVG = buildMarkersSVG(markers, scale);

  // ==================== SVG OUTPUT ====================

  return `<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${width}" height="${height}"
  viewBox="0 0 ${width} ${height}"
  style="display:block;"
>
  <!-- Map data © OpenStreetMap contributors, ODbL -->
  <image href="${mapUrl}" x="0" y="0" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet"/>
  ${landSVG}
  ${trailSVG}
  ${markerSVG}
</svg>`;
}

// ==================== COORDINATE EXPORT ====================
// Exported so pdf-generator and TrailMiniMap can use the same constants.

export const RESORT_BOUNDS = { north: NORTH, south: SOUTH, east: EAST, west: WEST };
export const RESORT_SVG_SIZE = { width: MAP_W, height: MAP_H };
