"use client";

// ==================== HOME ILLUSTRATIONS ====================
// Renders the Home page's mid-century artwork. The art itself lives in
// art/home-illustrations/*.svg (editable in Figma/Inkscape) and is imported
// into ./generated by scripts/import-illustrations.mjs, which also bakes in
// the motion from motion.json as CSS classes. The animations themselves are
// the .illo-* rules in globals.css; this file only decides when they run.

import { useCallback, useEffect, useRef, useState } from "react";
import { useReducedMotion } from "framer-motion";

export interface IlloArtData {
  label: string;
  svg: string;
}

type MotionMode = "still" | "animate" | "forced";

/**
 * "still" when the viewer's system asks for reduced motion. Dev builds
 * accept `?motion=on` ("forced") to preview animation on a machine with
 * Reduce Motion turned on. Until mounted it reports "animate", so the
 * server-rendered markup and the first client render match.
 */
export function useMotionMode(): MotionMode {
  const reduce = useReducedMotion() ?? false;
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted || !reduce) return "animate";
  if (process.env.NODE_ENV === "production") return "still";
  return new URLSearchParams(window.location.search).get("motion") === "on" ? "forced" : "still";
}

function withAlign(svg: string, align?: string): string {
  return align ? svg.replace(/preserveAspectRatio="[^"]*"/, `preserveAspectRatio="${align}"`) : svg;
}

/** The artwork itself. Changing `play` remounts it, which restarts the CSS animations. */
export function IlloArt({ art, play = 0, align }: { art: IlloArtData; play?: number; align?: string }) {
  const mode = useMotionMode();
  const className = mode === "still" ? "illo" : mode === "forced" ? "illo illo-animate illo-force" : "illo illo-animate";
  return (
    <div
      key={play}
      className={className}
      style={{ position: "absolute", inset: 0 }}
      // Our own generated artwork (see file header), never user content.
      dangerouslySetInnerHTML={{ __html: withAlign(art.svg, align) }}
    />
  );
}

/** Scenes play once on load; a hover replays them, at most this often. */
const REPLAY_COOLDOWN_MS = 2600;

/** A Home card scene: labelled for screen readers, replays on hover. */
export function IlloScene({ art }: { art: IlloArtData }) {
  const mode = useMotionMode();
  const [play, setPlay] = useState(0);
  const lastPlay = useRef(0);

  const replay = useCallback(() => {
    const now = Date.now();
    if (mode === "still" || now - lastPlay.current < REPLAY_COOLDOWN_MS) return;
    lastPlay.current = now;
    setPlay((n) => n + 1);
  }, [mode]);

  return (
    <div className="absolute inset-0" onMouseEnter={replay} role="img" aria-label={art.label}>
      <IlloArt art={art} play={play} />
    </div>
  );
}
